# Generated by Django 4.0.2 on 2022-11-15 14:02

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=48, null=True)),
                ('short_id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=8, max_length=8, prefix='', unique=True)),
                ('bucket_id', shortuuid.django_fields.ShortUUIDField(alphabet=['2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'], length=8, max_length=8, prefix='', unique=True)),
            ],
        ),
    ]
