# Generated by Django 4.0.2 on 2022-11-15 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='view',
            old_name='video',
            new_name='recording',
        ),
    ]
